# Generated by Django 5.2.7 on 2025-11-11 17:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('imagem', models.ImageField(upload_to='banners/%Y/%m/', verbose_name='Imagem do Banner')),
                ('link', models.URLField(blank=True, verbose_name='Link (opcional)')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem de Exibição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
                'ordering': ['ordem', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Beneficio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icone', models.CharField(default='fas fa-truck', help_text='Classe do ícone FontAwesome', max_length=50, verbose_name='Ícone')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título Principal')),
                ('subtitulo', models.CharField(blank=True, max_length=200, verbose_name='Subtítulo')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Benefício',
                'verbose_name_plural': 'Benefícios',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Categoria')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL Amigável')),
                ('imagem', models.ImageField(upload_to='categorias/%Y/%m/', verbose_name='Imagem')),
                ('tipo', models.CharField(choices=[('mais_procurado', 'Mais Procurado'), ('especie', 'Categoria por Espécie')], default='mais_procurado', max_length=20, verbose_name='Tipo')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('imagem', models.ImageField(upload_to='ofertas/%Y/%m/', verbose_name='Imagem da Oferta')),
                ('link', models.URLField(blank=True, verbose_name='Link')),
                ('data_inicio', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Início da Oferta')),
                ('data_fim', models.DateTimeField(blank=True, null=True, verbose_name='Fim da Oferta')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Oferta',
                'verbose_name_plural': 'Ofertas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServicoDestaque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Serviço')),
                ('imagem', models.ImageField(upload_to='servicos_destaque/%Y/%m/', verbose_name='Imagem do Local')),
                ('avaliacao', models.ImageField(upload_to='avaliacoes/', verbose_name='Imagem de Avaliação')),
                ('localizacao', models.CharField(max_length=200, verbose_name='Localização')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('preco_inicial', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Preço Inicial (R$)')),
                ('link', models.URLField(blank=True, verbose_name='Link para o Serviço')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Serviço em Destaque',
                'verbose_name_plural': 'Serviços em Destaque',
                'ordering': ['ordem', '-created_at'],
            },
        ),
    ]
