# Generated by Django 5.2.7 on 2025-11-11 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Pet')),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True)),
                ('especie', models.CharField(choices=[('cao', 'Cão'), ('gato', 'Gato'), ('ave', 'Ave'), ('roedor', 'Roedor'), ('reptil', 'Réptil'), ('outro', 'Outro')], max_length=20, verbose_name='Espécie')),
                ('raca', models.CharField(blank=True, max_length=100, verbose_name='Raça')),
                ('porte', models.CharField(choices=[('mini', 'Mini'), ('pequeno', 'Pequeno'), ('medio', 'Médio'), ('grande', 'Grande'), ('gigante', 'Gigante')], max_length=20, verbose_name='Porte')),
                ('sexo', models.CharField(choices=[('M', 'Macho'), ('F', 'Fêmea')], max_length=1, verbose_name='Sexo')),
                ('idade_anos', models.PositiveIntegerField(default=0, verbose_name='Idade (anos)')),
                ('idade_meses', models.PositiveIntegerField(default=0, verbose_name='Idade (meses)')),
                ('cor', models.CharField(blank=True, max_length=50, verbose_name='Cor')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('temperamento', models.CharField(blank=True, max_length=200, verbose_name='Temperamento')),
                ('foto_principal', models.ImageField(upload_to='pets/%Y/%m/', verbose_name='Foto Principal')),
                ('castrado', models.BooleanField(default=False, verbose_name='Castrado')),
                ('vacinado', models.BooleanField(default=False, verbose_name='Vacinado')),
                ('vermifugado', models.BooleanField(default=False, verbose_name='Vermifugado')),
                ('necessidades_especiais', models.TextField(blank=True, verbose_name='Necessidades Especiais')),
                ('status', models.CharField(choices=[('disponivel', 'Disponível'), ('adotado', 'Adotado'), ('processo', 'Em Processo de Adoção')], default='disponivel', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pet',
                'verbose_name_plural': 'Pets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PromocaoAdocao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('banner', models.ImageField(upload_to='promocoes/%Y/%m/', verbose_name='Banner')),
                ('data_inicio', models.DateField(verbose_name='Data de Início')),
                ('data_fim', models.DateField(verbose_name='Data de Término')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Promoção de Adoção',
                'verbose_name_plural': 'Promoções de Adoção',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='SolicitacaoAdocao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=200, verbose_name='Nome Completo')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('endereco', models.TextField(verbose_name='Endereço')),
                ('tipo_moradia', models.CharField(choices=[('casa', 'Casa'), ('apartamento', 'Apartamento'), ('sitio', 'Sítio/Chácara')], max_length=50, verbose_name='Tipo de Moradia')),
                ('tem_quintal', models.BooleanField(default=False, verbose_name='Tem Quintal')),
                ('moradia_propria', models.BooleanField(default=False, verbose_name='Moradia Própria')),
                ('tem_outros_pets', models.BooleanField(default=False, verbose_name='Tem Outros Pets')),
                ('descricao_outros_pets', models.TextField(blank=True, verbose_name='Descrição dos Outros Pets')),
                ('teve_pets_antes', models.BooleanField(default=False, verbose_name='Já Teve Pets Antes')),
                ('motivacao', models.TextField(verbose_name='Por que deseja adotar?')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('analise', 'Em Análise'), ('aprovada', 'Aprovada'), ('recusada', 'Recusada')], default='pendente', max_length=20, verbose_name='Status')),
                ('observacoes_admin', models.TextField(blank=True, verbose_name='Observações da Administração')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Solicitação de Adoção',
                'verbose_name_plural': 'Solicitações de Adoção',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FotoPet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='pets/%Y/%m/')),
                ('descricao', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos_adicionais', to='pets.pet')),
            ],
            options={
                'verbose_name': 'Foto do Pet',
                'verbose_name_plural': 'Fotos dos Pets',
            },
        ),
    ]
