# Generated by Django 5.2.7 on 2025-11-11 17:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='promocaoadocao',
            name='criado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promocoes_criadas', to=settings.AUTH_USER_MODEL, verbose_name='Criado Por'),
        ),
        migrations.AddField(
            model_name='solicitacaoadocao',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes', to='pets.pet', verbose_name='Pet'),
        ),
        migrations.AddField(
            model_name='solicitacaoadocao',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes_adocao', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
    ]
