# Generated by Django 5.2.7 on 2025-11-11 17:23

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Categoria')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL Amigável')),
                ('tipo', models.CharField(choices=[('alimentos', 'Alimentos'), ('brinquedos', 'Brinquedos'), ('gaiolas_viveiros', 'Gaiolas e Viveiros'), ('roupas_acessorios', 'Roupas e Acessórios'), ('higiene', 'Higiene'), ('outros', 'Outros')], max_length=30, verbose_name='Tipo')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='categorias/%Y/%m/', verbose_name='Imagem')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem de Exibição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoria de Produto',
                'verbose_name_plural': 'Categorias de Produtos',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Produto')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='URL Amigável')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('imagem_principal', models.ImageField(upload_to='produtos/%Y/%m/', verbose_name='Imagem Principal')),
                ('preco_original', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Preço Original (R$)')),
                ('preco_desconto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Preço com Desconto (R$)')),
                ('estoque', models.PositiveIntegerField(default=0, verbose_name='Quantidade em Estoque')),
                ('estoque_minimo', models.PositiveIntegerField(default=5, verbose_name='Estoque Mínimo')),
                ('avaliacao', models.DecimalField(decimal_places=1, default=Decimal('5.0'), max_digits=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Avaliação (0-5)')),
                ('numero_avaliacoes', models.PositiveIntegerField(default=0, verbose_name='Número de Avaliações')),
                ('peso_tamanho', models.CharField(blank=True, max_length=50, verbose_name='Peso/Tamanho')),
                ('marca', models.CharField(default='SmartPaws', max_length=100, verbose_name='Marca')),
                ('destaque', models.BooleanField(default=False, verbose_name='Produto em Destaque')),
                ('novidade', models.BooleanField(default=False, verbose_name='Novidade')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='produtos.categoriaproduto', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImagemProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='produtos/galeria/%Y/%m/', verbose_name='Imagem')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens_adicionais', to='produtos.produto', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Imagem do Produto',
                'verbose_name_plural': 'Imagens dos Produtos',
                'ordering': ['ordem'],
            },
        ),
        migrations.AddIndex(
            model_name='produto',
            index=models.Index(fields=['slug'], name='produtos_pr_slug_e58355_idx'),
        ),
        migrations.AddIndex(
            model_name='produto',
            index=models.Index(fields=['categoria', 'ativo'], name='produtos_pr_categor_409cd5_idx'),
        ),
    ]
