# Generated by Django 5.2.8 on 2025-11-12 01:09

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True)),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('icone', models.CharField(blank=True, help_text='Classe do ícone FontAwesome', max_length=50)),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem de Exibição')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoria de Serviço',
                'verbose_name_plural': 'Categorias de Serviços',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Prestador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('logo', models.ImageField(blank=True, upload_to='prestadores/%Y/%m/', verbose_name='Logo')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('whatsapp', models.CharField(blank=True, max_length=20, verbose_name='WhatsApp')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('site', models.URLField(blank=True, verbose_name='Site')),
                ('endereco', models.CharField(max_length=300, verbose_name='Endereço')),
                ('bairro', models.CharField(max_length=100, verbose_name='Bairro')),
                ('cidade', models.CharField(max_length=100, verbose_name='Cidade')),
                ('estado', models.CharField(max_length=2, verbose_name='Estado')),
                ('cep', models.CharField(blank=True, max_length=9, verbose_name='CEP')),
                ('avaliacao_media', models.DecimalField(decimal_places=2, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Avaliação Média')),
                ('total_avaliacoes', models.PositiveIntegerField(default=0, verbose_name='Total de Avaliações')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('destaque', models.BooleanField(default=False, verbose_name='Destaque')),
                ('verificado', models.BooleanField(default=False, verbose_name='Verificado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Prestador',
                'verbose_name_plural': 'Prestadores',
                'ordering': ['-destaque', '-avaliacao_media', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Serviço')),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('descricao_curta', models.CharField(blank=True, max_length=200, verbose_name='Descrição Curta')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço')),
                ('unidade_tempo', models.CharField(choices=[('hora', 'Por hora'), ('dia', 'Por dia'), ('semana', 'Por semana'), ('mes', 'Por mês'), ('servico', 'Por serviço')], default='servico', max_length=20, verbose_name='Unidade de Tempo')),
                ('duracao', models.CharField(blank=True, max_length=100, verbose_name='Duração Estimada')),
                ('inclui', models.TextField(blank=True, verbose_name='O que está incluído')),
                ('requisitos', models.TextField(blank=True, verbose_name='Requisitos')),
                ('imagem_principal', models.ImageField(upload_to='servicos/%Y/%m/', verbose_name='Imagem Principal')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('destaque', models.BooleanField(default=False, verbose_name='Destaque')),
                ('disponibilidade', models.CharField(blank=True, max_length=200, verbose_name='Disponibilidade')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicos', to='servicos.categoriaservico', verbose_name='Categoria')),
                ('prestador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicos', to='servicos.prestador', verbose_name='Prestador')),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
                'ordering': ['-destaque', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgendamentoServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_agendamento', models.DateField(verbose_name='Data do Agendamento')),
                ('horario', models.TimeField(verbose_name='Horário')),
                ('nome_pet', models.CharField(max_length=100, verbose_name='Nome do Pet')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('confirmado', 'Confirmado'), ('em_andamento', 'Em Andamento'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='pendente', max_length=20, verbose_name='Status')),
                ('observacoes_prestador', models.TextField(blank=True, verbose_name='Observações do Prestador')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to='servicos.servico', verbose_name='Serviço')),
            ],
            options={
                'verbose_name': 'Agendamento',
                'verbose_name_plural': 'Agendamentos',
                'ordering': ['-created_at'],
            },
        ),
    ]
