# Generated by Django 5.2.8 on 2025-11-14 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='imagem_principal',
            field=models.ImageField(blank=True, null=True, upload_to='servicos/%Y/%m/', verbose_name='Imagem Principal'),
        ),
    ]
